# =============================================================================
# ENVIRONMENT VALIDATION WORKFLOW - .github/workflows/validate-environment.yml
# =============================================================================

name: ✅ Validate Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to validate'
        required: true
        type: choice
        options: [dev, preprod, prod]
      validation_type:
        description: 'Validation type'
        required: true
        type: choice
        options: [pre-deployment, post-deployment, complete-integration]
        default: complete-integration

jobs:
  validate_environment:
    name: ✅ Environment Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 botocore

      - name: 🎯 Determine Environment Configuration
        id: env_config
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          case $ENVIRONMENT in
            "dev")
              SAGEMAKER_ROLE_ARN="arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/sdcp-dev-sagemaker-energy-forecasting-datascientist-role"
              ;;
            "preprod")
              SAGEMAKER_ROLE_ARN="arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/sdcp-preprod-sagemaker-energy-forecasting-datascientist-role"
              ;;
            "prod")
              SAGEMAKER_ROLE_ARN="arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/sdcp-prod-sagemaker-energy-forecasting-datascientist-role"
              ;;
          esac
          echo "sagemaker_role_arn=$SAGEMAKER_ROLE_ARN" >> $GITHUB_OUTPUT

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.env_config.outputs.sagemaker_role_arn }}
          role-session-name: energy-forecasting-validation-${{ github.run_id }}
          aws-region: us-west-2

      - name: ✅ Run Environment Validation
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          VALIDATION_TYPE: ${{ github.event.inputs.validation_type }}
        run: |
          echo "=== ENVIRONMENT VALIDATION ==="
          echo "Environment: $ENVIRONMENT"
          echo "Validation Type: $VALIDATION_TYPE"
          echo "============================="

          case $VALIDATION_TYPE in
            "pre-deployment")
              python sdcp_code/deployment/validate_environment.py \
                --environment $ENVIRONMENT \
                --pre-deployment-check
              ;;
            "post-deployment")
              python sdcp_code/deployment/validate_environment.py \
                --environment $ENVIRONMENT \
                --post-deployment-check
              ;;
            "complete-integration")
              python sdcp_code/deployment/validate_environment.py \
                --environment $ENVIRONMENT \
                --complete-integration-check
              ;;
          esac

      - name: 📝 Upload Validation Results
        uses: actions/upload-artifact@v4
        with:
          name: validation-results-${{ github.event.inputs.environment }}-${{ github.run_id }}
          path: validation-results-*.json
          retention-days: 90
